Revert "Use "for_each" to loop through "domain_validation_options" (#6)" (#9)
This reverts commit c56b7172bb645a4d7b8265040b46401b1c786a48.

We need to only do validations when we are creating a certificate.
In cases where we do not create a certificate this change fails.
```
Error: Invalid index

  on ./network.tf line 257, in resource "aws_route53_record" "cert_validation":
 257:     for dvo in aws_acm_certificate.cert[0].domain_validation_options : dvo.domain_name => {
    |----------------
    | aws_acm_certificate.cert is empty tuple

The given key does not identify an element in this collection value.
```